### ISSUE TITLE
Remove dependency on torchtext for dianna

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#357]
Importing dianna now requires torchtext. I think we should somehow make this optional. Dianna shouldn't require installing TF or torch components. We could try to get rid of this dependency for instance by not importing tokenizers in the misc module. 

```
PS C:\Users\ChristiaanMeijer\Documents\robot_or_brain\robot_or_brain> python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dianna
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ChristiaanMeijer\AppData\Roaming\Python\Python38\site-packages\dianna\__init__.py", line 26, in <module>
    from . import utils
  File "C:\Users\ChristiaanMeijer\AppData\Roaming\Python\Python38\site-packages\dianna\utils\__init__.py", line 8, in <module>
    from .tokenizers import SpacyTokenizer
  File "C:\Users\ChristiaanMeijer\AppData\Roaming\Python\Python38\site-packages\dianna\utils\tokenizers.py", line 4, in <module>
    from torchtext.data import get_tokenizer
ModuleNotFoundError: No module named 'torchtext'
```

**Comment by loostrum** [comment]
Agreed with removing the hard requirement on torchtext. Perhaps another variant may be of use here? dianna[text]?
Although too many variants would be confusing as well.

I'm not sure we can remove the tensorflow requirements, I think KernelSHAP needs it (which is also why that method can only run with an input onnx file and not a function)
