### ISSUE TITLE
Could not install dianna-dashboard

### ISSUE THREAD

**Issue by laurasootes** [dianna-ai/dianna#583]
I cannot install the dashboard using pip3 install -e .'[dashboard]' on my Mac (M2 chip).
The problem comes from the build of the wheels for grpcio. So far I cannot find how to solve this.

@stefsmeets do you have an idea how to solve this?

Output:

      copying python_build/lib.macosx-10.10-x86_64-cpython-310/grpc/_plugin_wrapping.py -> python_build/bdist.macosx-10.10-x86_64/wheel/grpc
      copying python_build/lib.macosx-10.10-x86_64-cpython-310/grpc/_interceptor.py -> python_build/bdist.macosx-10.10-x86_64/wheel/grpc
      copying python_build/lib.macosx-10.10-x86_64-cpython-310/grpc/_grpcio_metadata.py -> python_build/bdist.macosx-10.10-x86_64/wheel/grpc
      copying python_build/lib.macosx-10.10-x86_64-cpython-310/grpc/_server.py -> python_build/bdist.macosx-10.10-x86_64/wheel/grpc
      copying python_build/lib.macosx-10.10-x86_64-cpython-310/grpc/_runtime_protos.py -> python_build/bdist.macosx-10.10-x86_64/wheel/grpc
      copying python_build/lib.macosx-10.10-x86_64-cpython-310/grpc/_auth.py -> python_build/bdist.macosx-10.10-x86_64/wheel/grpc
      running install_egg_info
      running egg_info
      writing src/python/grpcio/grpcio.egg-info/PKG-INFO
      writing dependency_links to src/python/grpcio/grpcio.egg-info/dependency_links.txt
      writing requirements to src/python/grpcio/grpcio.egg-info/requires.txt
      writing top-level names to src/python/grpcio/grpcio.egg-info/top_level.txt
      reading manifest file 'src/python/grpcio/grpcio.egg-info/SOURCES.txt'
      reading manifest template 'PYTHON-MANIFEST.in'
      warning: no files found matching '*.c' under directory 'src/python/grpcio/grpc'
      warning: no files found matching '*.h' under directory 'src/python/grpcio/grpc'
      warning: no files found matching '*.inc' under directory 'src/python/grpcio/grpc'
      warning: no files found matching '*.python' under directory 'src/python/grpcio/grpc'
      warning: no previously-included files matching '*.so' found under directory 'src/python/grpcio/grpc/_cython'
      warning: no previously-included files matching '*.pyd' found under directory 'src/python/grpcio/grpc/_cython'
      warning: no files found matching 'src/python/grpcio/precompiled.py'
      adding license file 'LICENSE'
      writing manifest file 'src/python/grpcio/grpcio.egg-info/SOURCES.txt'
      Copying src/python/grpcio/grpcio.egg-info to python_build/bdist.macosx-10.10-x86_64/wheel/grpcio-1.54.0-py3.10.egg-info
      running install_scripts
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/8c/9kvl108j7993913rb6tjw5cm0000gn/T/pip-install-oevzcv95/grpcio_686d33d0e0f647a5a53030d9541c8c41/setup.py", line 537, in <module>
          setuptools.setup(
        File "/opt/miniconda3/envs/dianna/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/opt/miniconda3/envs/dianna/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/opt/miniconda3/envs/dianna/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/miniconda3/envs/dianna/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/opt/miniconda3/envs/dianna/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/opt/miniconda3/envs/dianna/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/miniconda3/envs/dianna/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 328, in run
          impl_tag, abi_tag, plat_tag = self.get_tag()
        File "/opt/miniconda3/envs/dianna/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
          assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
      AssertionError: would build wheel with unsupported tag ('cp310', 'cp310', 'macosx_10_10_x86_64')
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio
  Running setup.py clean for grpcio
Failed to build grpcio
ERROR: Could not build wheels for grpcio, which is required to install pyproject.toml-based projects

**Comment by laurasootes** [comment]
I managed to solve the issue by installing grpcio using conda:

``pip uninstall grpcio``
``conda install grpcio``
